const keywords = {
  automation: [
    "automation",
    "A.I.",
    "artificial",
    "Intelligence",
    "layoffs",
    "workforce reduction",
    "robot",
    "robotic",
    "robotics",
    "AGI",
    "machines",
    "AI",
    "transformation",
    "digitisation",
    "autonomous",
    "technology",
    "recession",
    "information",
    "innovation",
    "conscious",
    "cyber",
    "5g",
    "disruption",
    "Tech",
  ],
  recession: ["recession", "policy"],
};

module.exports = { keywords };
